import { useContext, useEffect, useState } from "react";
import { GetServerSideProps, GetStaticProps, NextPage } from 'next';
import Head from 'next/head'
import Recommende from '@component/components/recommende/Recommende';
import getRecommende from '@component/helpers/getRecommende';
import { RecommendFivesongs } from '@component/interfaces/recommende.interface';
import { TokenContext } from "@component/context";

interface Props {
    data: RecommendFivesongs,
}

const Home: NextPage<Props> = ({ data }) => {

    const context = useContext(TokenContext);

    useEffect(() => {
        const hash = window.location.hash
        let tokenURL = window.localStorage.getItem("token")
        if (!tokenURL && hash) {
            tokenURL = hash.substring(1).split("&").find(elem => elem.startsWith("access_token"))!.split("=")[1];
            window.location.hash = ""
            window.localStorage.setItem("token", tokenURL);
            console.log(tokenURL);

            context?.setToken(tokenURL);
        }
    }, []);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="container mt-[90px]">
                <div className='flex flex-col w-full lg:w-[70%]'>
                    <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
                        Bienvenido a TO MUSIC Frontend
                    </h1>
                    <p className="relative mt-6 text-lg leading-8 text-gray-600 sm:max-w-md lg:max-w-none">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, maiores. Asperiores culpa ipsam labore sunt soluta excepturi atque perspiciatis aliquid vero commodi saepe esse, accusantium deleniti quas ipsa placeat eligendi?
                    </p>
                </div>
                {data &&
                    <Recommende data={data} />
                }
            </div>
        </>
    )
}

export const getServerSideProps: GetServerSideProps = async ({ req, query }) => {

    const data = await getRecommende();
    return {
        props: {
            data,
        },
    }
}
export default Home;
